// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package configs

import (
	"github.com/google/wire"
	"yab-explorer/controllers"
	"yab-explorer/repository"
	"yab-explorer/services"
)

// Injectors from injector.go:

func Init() *Initialization {
	gormDB := ConnectToDB()
	orderRepositoryImpl := repository.OrderRepositoryInit(gormDB)
	orderServiceImpl := services.OrderServiceInit(orderRepositoryImpl)
	orderControllerImpl := controllers.OrderControllerInit(orderServiceImpl)
	initialization := NewInitialization(orderRepositoryImpl, orderServiceImpl, orderControllerImpl)
	return initialization
}

// injector.go:

var db = wire.NewSet(ConnectToDB)

var orderServiceSet = wire.NewSet(services.OrderServiceInit, wire.Bind(new(services.OrderService), new(*services.OrderServiceImpl)))

var orderRepositorySet = wire.NewSet(repository.OrderRepositoryInit, wire.Bind(new(repository.OrderRepository), new(*repository.OrderRepositoryImpl)))

var orderControllerSet = wire.NewSet(controllers.OrderControllerInit, wire.Bind(new(controllers.OrderController), new(*controllers.OrderControllerImpl)))
